### PR TITLE
added a list for tags, in alphabetical order

### PR DESCRIPTION
**Pull request by arispress88**
### **Description**

Added "TAG MANAGEMENT" to the nav bar, when user clicks the link, they are taken to a page with a list of available tags.

Created `Tag.cs`, `TagController.cs`, `TagRepository.cs`
, and `ITagRepository.cs`. As well as added `Index.cshtml` under the `Views` Directory in the `Tag` Folder.

### **Fixes # (issue)**

Ticket https://trello.com/c/ZGtTiXJx/13-13-view-all-tags

### **Type of change**

- [ x ]  New feature (non-breaking change which adds functionality)

### **Testing Instructions**

- Reference [How to test a teammate's PR](https://gist.github.com/jordan-castelloe/96f76d5bd4cfbd2181084af674c2a1af#when-you-need-to-test-a-teammates-pr)
- Log in using [admin@example.com](mailto:admin@example.com)
- Make sure to add all [seed data](https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/tree/main/SQL) before testing
- Add the [seed data](https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/tree/main/SQL) by opening the SQL Server marked as "SQLEXPRESS" in the SQL Server Object Explorer on the left side of Visual Code. Once there, add a new SQL server by selecting the 'Add SQL Server' option at the top of the side bar. Copy the data from the [seed data](https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/tree/main/SQL) and execute by pressing the green Play button.
- Click on Tag Management in the NavBar
- View the list of available Tags (tags should appear in alphabetical order)
- To verify and compare what is showing in the browser matches the database, run a SQL Query: SELECT * FROM Tag ORDER BY Name ASC
- Available list of tags, in alphabetical order, from seed data should be:
- C#, CyclopeanTerrors, Family, JavaScript (No additional Tags have been added at this time)

### **Checklist**

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings or errors
- [ x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- We want to be super explicit in our testing instructions and go step by step including git in them 
- Please look at the gist and include exactly what the user should see when they test their code (this can also be a SQL query)

**Comment by Tommy-Spurlock** [comment]
Better, but please include instructions on how to add seed data

**Comment by Tommy-Spurlock** [comment]
Again, much better instructions. This gets the 👍 from me but let's be even more descriptive on future pull request.

**Comment by spencer-lott** [comment]
Tested it arnold. Looks good!

**Pull request merged**
