### PR TITLE
Edit Tags (Ticket #16)

### PR DESCRIPTION
**Pull request by arispress88**
## Description
This pull request is for TabloidMVC.

Trello ticket #16 - https://trello.com/c/cvATmGIe/16-16-edit-a-tag

The branch for the pull request: `<ar-tabloid>`

The user is able to edit the tags in the list

## Updates:
Added method `UpdateTag()` to `TagRepository.cs`
Added above method to `ITagRepository.cs`
Added a View called `Edit.cshtml` for Tag views folder
Updated the Edit GET and POST methods in `TagController.cs`

## Type of change:
[ x ] New feature (non-breaking change which adds functionality)

## Testing Instructions:

- Follow these instructions to protect the branch you are working on and to test this pull request: https://gist.github.com/jordan-castelloe/96f76d5bd4cfbd2181084af674c2a1af#when-you-need-to-test-a-teammates-pr
- If you do not currently have the code for this project, clone the repository - https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys.

Open the TabloidMVC.sln in visual studio
• In the github repository: https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys

• Open the SQL folder: https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/tree/main/SQL

• there are two files - [01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/blob/main/SQL/01_TabloidMVC_Create_DB.sql) and [02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)

• In Visual Studio in the top navbar click View and select SQL Server Object Explorer. Open the server marked as "SQLEXPRESS" in the SQL Server Object Explorer on the left side of Visual Code. Once there, add a new SQL server by selecting the 'Add SQL Server' option at the top of the side bar. Copy the data from the [seed data](https://github.com/NewForce-Cohort-7/tabloidmvc-lone-star-cowboys/tree/main/SQL). Prepare your database.

• execute by pressing the green Play button.

• start the server by clicking the solid green play button in the middle top of your screen. A browser window will display with the Tabloid landing page.

• In the nav bar, click Login. You only need an email to login use [admin@example.com](mailto:admin@example.com)

• You now see the home page for the site. In the navbar, click on "Tag Management"

You will see the Tags page with the following tags in alphabetical order: "C#", "Cyclopean Terrors", "Family", and "JavaScript".

1. Click the blue button marked "New Tag"
2. Choose a name for your Tag (i.e. "Food")
3. Save the new tag by clicking the blue "SAVE" button.
4. Once redirected to `/Tag/Index` check to see if your new tag is listed in alphabetical order.
5. Click on the pencil icon next to the tag you created. This will take you to `/Tag/Edit`.
6. Change the name of your tag (i.e. "Pizza").
7. Once the changes are made, click the blue "SAVE" button.
8. You will be redirected to `/Tag/Index`

If you would like to further test this or test it through a SQL query, create a query for the database you created at the start of the pull request testing. In your new query, paste:

```sql

// First, run the following query //
INSERT INTO Tag (Name) VALUES ('YourTag')

// Then, choose a tag to change //
UPDATE Tag SET Name = 'NewTagName' WHERE Id = 'YourTagId'

// After running the previous query, check to see if the update was successful //
SELECT * FROM Tag
```

After running the query (the green play button on the left of the query window) you should see the updated name to the tag you edited.

### CODE REVIEW

**Comment by kathleentyner** [comment]
Works for me!

**Comment by spencer-lott** [comment]
Good to go on my end!

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- We want to protect our data so we should have dummy data to edit instead of editing data that exists in our DB currently
- Please look at the SQL statement you have and I think you don't want to actually run an update statement nor would that statement work, but maybe you want a Select statement to see if something did edit in the database correctly?

**Review by sarahebrooks12 — APPROVED** [review]
Looks good 👼

**Pull request merged**
